title:              Sean's Blog
email:              mgshawn.t@gmail.com
description:        A Blog Theme by Start Bootstrap
author:             mgshawn
baseurl:            "/"
url:                "https://magicshawn.github.io"

# Social Profiles
twitter_username:   mgshawn
github_username:    MagicShawn
facebook_username:  mgshawn
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           GFM
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
